CREATE LOGIN [om_user]
    WITH PASSWORD = N'pLXzXfvp`fCUoikpxHug7{mcmsFT7_&#$!~<kDfb~xrih|pi', SID = 0xC478530B181C6C4BA6FD70BE00CCBD43, DEFAULT_DATABASE = [DotNetDb], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

